### PR TITLE
german translation of 1/2

### PR DESCRIPTION
**Pull request by afink70**
add german translation

### CODE REVIEW

**Comment by vasa-develop** [comment]
@afink70 not sure if this is the problem with google translate, but somehow the word "contract" to converted to "mission" after translation.

**German:** "Jetzt, wo wir eine Hülle für unseren Auftrag haben, wollen wir erfahren, wie Vyper mit Variablen umgeht."
**English (Generated):** Now that we have a shell for our mission, let's learn how Vyper handles variables.
**English (Expected):** Now that we've got a shell for our contract, let's learn about how Vyper deals with variables.

As "contract" is an important term in smart contracts, we need to preserve the word after the translation. 

Similar issues with terms like "state variables" and "contract storage".

**German:** Zustandsvariablen sind permanent im Auftragsspeicher gespeichert.
**English (Generated):** Status variables are permanently stored in the job memory.
**English (Expected):** State variables are permanently stored in contract storage.

Can you look through such issues and update your pull request? Let me know if you need any help :smile:

**Comment by finki70** [comment]
Okay, sorry, I'll change it later. The problem is from my point of view the german language, you can translate a word into some others. Do you mean `A contract is a legally binding document that recognizes and governs the rights and duties of the parties to the agreement` with 'contract'? I translated it and understood it different.

Zustandsvariablen means

state + variable
,I'll change it to Job memory

**Comment by afink70** [comment]
Okay, sorry, I'll change it later. The problem is from my point of view the german language, you can translate a word into some others. Do you mean `A contract is a legally binding document that recognizes and governs the rights and duties of the parties to the agreement` with 'contract'? I translated it and understood it different.

[Zustandsvariablen](https://www.dict.cc/?s=Zustandsvariable) means

state + variable
, I'll change job memory.

**Comment by vasa-develop** [comment]
@afink70 Here `contract` has a bit different meaning. Basically, a single file of Vyper is called a contract. (The idea of a contract is similar to what you mentioned above: `a legally binding document`, but here the "code is law" and once a contract is deployed it is not supposed to change. Hence it was given the name: `contract`)

So, basically `contract` is sort of a keyword.

Just ping me once when you are done with the changes  :smile:

**Comment by afink70** [comment]
@vasa-develop I think its ready to merge, I changed it to contract & #24 should be right as it was :)

**Comment by vasa-develop** [comment]
Will merge it tomorrow :)

**Pull request merged**
